version: '3.4'

services:
  unik_onboarding.webapp:
    ports:
      - "32333:80"
    image: ${DOCKER_REGISTRY-}unikonboardingwebapp
    build: 
      context: .
      dockerfile: Unik_OnBoarding.WebApp\Dockerfile
    environment:
         "ASPNETCORE_ENVIRONMENT": "Development"
         "ConnectionStrings:UserAppConnection": "Server=db;Database=Unik_OnBoarding_UserDB;user id=sa;password=SqlPassw0rd!; MultipleActiveResultSets=true"     
         "UnikBaseUrl" : "http://unik_onboarding.api"
    depends_on:
      - db
      - unik_onboarding.api

  unik_onboarding.api:
    ports:
      - "32330:80"
    image: ${DOCKER_REGISTRY-}unikonboardingapi
    build:
      context: .
      dockerfile: Unik_OnBoarding.Api\Dockerfile
    environment:
         "ASPNETCORE_ENVIRONMENT": "Development"
         "ConnectionStrings:AppConnectionString": "Server=db;Database=Unik_OnBoardingDB;user id=sa;password=SqlPassw0rd!; MultipleActiveResultSets=true"

    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    ports:
      - "14330:1433"
    environment:
        MSSQL_SA_PASSWORD: "SqlPassw0rd!"
        ACCEPT_EULA: "Y"

    volumes:
      - C:\Temp\SqlVolumeUnik\data:/var/opt/mssql/data
      - C:\Temp\SqlVolumeUnik\log:/var/opt/mssql/log
      - C:\Temp\SqlVolumeUnik\secrets:/var/opt/mssql/secrets 

    container_name: sql2019
    hostname: sql1