using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Unik_OnBoarding.Domain.Model;

public class KundeEntity
{
    [Key] // Server side validation
    public Guid Kid { get; set; } // autogenerated unik number med Bogstaver og number

    [Required]
    [DisplayName("Erhvervs navn")]
    public string Name { get; set; }

    [Required][EmailAddress] public string Email { get; set; }

    [Required][Phone] public int Telefon { get; set; }

    [Required] public string Adresse { get; set; }

    // Navigation prop
    public List<ProjektEntity>? Projekt { get; set; } // En kunde kunde har null eller flere Projekt (derfor har vi set et ?)

    [Timestamp]
    public byte[] RowVersion { get; set; }
}