using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Unik_OnBoarding.Application.Implementation.Kunde.dto;

public class KundeCreateDto
{
    [Key] // Server side validation
    public Guid Kid { get; set; } // autogenerated unik number med Bogstaver og number

    [Required]
    [DisplayName("Erhvervs navn")]
    public string Name { get; set; }

    [Required]
    [EmailAddress]
    public string Email { get; set; }

    [Required]
    [Phone]
    public int Telefon { get; set; }
}